### ISSUE TITLE
about the RPY

### ISSUE THREAD

**Issue by wukongwong** [ElectronicElephant/pybullet_ur5_robotiq#1]
Hi,
Thanks for providing a good simulation. I just checked the RPY control, found only Y works, RP not. So I just wonder whether it's code like this, or there is some bug?

**Comment by ElectronicElephant** [comment]
Hello Wukong,

Thanks for reaching me.

I mainly focus on the so-called Top-Down pushing and grasping, so RP are fixed by default, in the Environment class.

See here

https://github.com/ElectronicElephant/pybullet_ur5_robotiq/blob/4356e143a1e91f75e6fd1c71693a0a7475a2f0bd/env.py#L199

Just comment out this line, and RP will work.

If you have more questions, feel free to contact me. Please don't forget to give me a star, if you like. 😆

**Comment by wukongwong** [comment]
It works now after I did as you just said. I need to check the code by myself actually. Thanks!
