### ISSUE TITLE
Question: how did you generate the pure urdf file

### ISSUE THREAD

**Issue by ghost** [ElectronicElephant/pybullet_ur5_robotiq#2]
Hi,

I apologize for asking a question here. But I was trying to generate a "pure" urdf file recently (to use openrave ikfast) but all I can find online is how to convert the macro file to urdf and this always gives me issues. 

I would appreciate a lot if you could share some suggestions or point me to the right direction. Thank you.

**Comment by ElectronicElephant** [comment]
Hi Kevin,

Thanks for reaching me. I noticed that you have opened another issue, where you said

```
I can find the ur5e.urdf.xacro and robotiq_140.urdf.xacro from the github. However, I just have a hard time putting them together as a single urdf file as what you have here. (The generated IKfast does not converge with my urdf file).
```

It's true that the urdf files are converted from xacro files. I don't know the details, because one of my friends helped me to convert. The whole progress requires ROS. This link seems to be promising. https://answers.ros.org/question/310297/arm-does-not-appear-when-using-xacro-to-attach-ur5-to-robotiq-gripper/?answer=310318#post-id-310318

If you don't mind, maybe you can paste the urdf file here and I can help check it.

Bests,

T.T. Tang
